### ISSUE TITLE
User can choose category to view data for

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/ajax-project#1]
## ⚙️ Functionality

Main page with placeholder search bar and buttons that allow user to choose which Rick and Morty category they'd like to look through.

## 🖼️ Wireframe

![Screen Shot 2021-02-22 at 5 12 10 PM](https://user-images.githubusercontent.com/76799878/108790278-233d4f80-7531-11eb-82ff-7bd620dd3a99.png)

## ✅ Task List

- [x] Add three rows to index.html, with rows 2 and 3 having a two column layout
- [x] Add the following buttons to their respective columns: characters, locations, episodes, and favorites
- [x] Find relevant images to pair with each button
- [x] Create img tags with src attributes linked to their respective image and add them to their corresponding columns
- [x] Add placeholder form and search bar input to first row
- [x] create the app header and background in CSS
- [x] recreate the layout seen in the wireframe in layout.css
- [x] ensure the search bar is properly placed and sized
- [x] ensure each image is properly cropped and sized
- [x] ensure each button is attached to it's corresponding image and properly sized
- [x] add media queries and ensure page looks good on desktop
- [x] add event listeners for each button/image pairs
- [x] finalize CSS
- [x] fix any errors
