### ISSUE TITLE
User can view a list of data for selected category

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/ajax-project#2]
## ⚙️ Functionality

Allows user to scroll through a page containing a list of the API data corresponding to the category they selected on the main page.

## 🖼️ Wireframe

![Screen Shot 2021-02-22 at 5 37 10 PM](https://user-images.githubusercontent.com/76799878/108791724-a2805280-7534-11eb-9d2b-6fbd1c4316e9.png)

## ✅ Task List

- [x] add code to click event function that adds the hidden class to the main page
- [x] create a hidden class in css with display set to none
- [x] add a div to the HTML with the class: "ajax list hidden" with a ul child element
- [x] in main.js, assign the ul element to a variable using queryselector
- [x] create a function in main.js called "createDOM" that builds a DOM tree with the following elements:
- [x]  - an li element
- [x]  - a div element with the class "column-25" and an img child element
- [x]  - a div element with the class "column-75" and an h2 child element
- [x] create a loadDOM function that loops through the results array of the API response and in the loop's code block:
- [x]  - use the createDOM function to create a DOM tree
- [x]  - append that dom tree to the ul element
- [x] create an ajax request with a load event listener that:
- [x]  - calls the loadDOM function
- [x]  - creates an event listner for DOM content loaded using the loadDOM function
- [x] call the ajax request function in each click event listener for the main page buttons
- [x] style the loaded list items in css to match the wireframe
- [x] finalize css
- [x] fix any errors
