### ISSUE TITLE
User can view entry page for a single result from category list

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/ajax-project#3]
## ⚙️ Functionality

Allows user to select an option from the category list, showing them an entry page containing various information about the character, location, or episode they have chosen.

## 🖼️ Wireframe

![Screen Shot 2021-02-22 at 5 41 26 PM](https://user-images.githubusercontent.com/76799878/108792026-38b47880-7535-11eb-912b-22934d2e598a.png)

## ✅ Task List

- [x] add an "createEntryDOM" function to main.js that creates a DOM tree with the following elements:
- [x]  - an img tag
- [x]  - an h1 tag for the name
- [x]  - a ul tag with li children for relevant details included in the api result for that character / location / etc
- [x] add a click event listener to main.js that:
- [x]  - detects which list item is clicked 
- [x]  - calls the createEntryDOM function with the detected item as an argument
- [x]  - hides the list page and shows the entry page
- [x] ensure that the entry page contains all necessary data
- [x] style the entry page to match the wireframe
- [x] create a "back" button, which allows the user to go to the previous page:
- [x]  - find an icon and add it to each page in the html with the class: "back-button"
- [x]  - add an event listener for button that hides the current page and shows the previous page
- [x]  - use absolute positioning to place the button in a good spot
- [x]  create directional buttons for the list page that load a new section of API data when pressed
- [x] add an event listener for the header, which brings the user back to the main page
- [x] finalize css
- [x] fix any errors
