### ISSUE TITLE
User can save entries to a 'Favorites' page and remove them

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/ajax-project#4]
## ⚙️ Functionality

Lets the user add entries to a favorites page, either from the category list or from the entry page. Once the entry has been added, it can be removed from the entry page.

## 🖼️ Wireframe

![Screen Shot 2021-02-22 at 5 46 16 PM](https://user-images.githubusercontent.com/76799878/108792400-07887800-7536-11eb-9129-a146a229fb48.png)

## ✅ Task List

- [x] create a data model in data.js with an array for each category to store saved entries
- [x] add the following to the createEntryDOM function:
- [x]  - var $saveButton, which creates a button element
- [x]  - give it the class 'save-button'
- [x]  - give the button the text content: "Save to Favorites"
- [x]  - append $saveButton to $entry
- [x] use css to style the button and ensure it looks nice in both mobile and desktop modes
- [x] add an event listener to main.js that detects when the save button is clicked and:
- [x]  - creates an object with all of the data stored in that entry
- [x]  - pushes the object into the correct data model array
- [x]  - hides the save button
- [x] create a function 'loadFavorites' which:
- [x] - adds the message 'no favorites added yet' to page if data model is empty
- [x]  - creates a section for each category
- [x]  - loops through each data array, calling the createDOM function with each array entry as an argument
- [x]  - appends new dom tree to page under corresponding category
- [x] add another if statement to categorySelect which:
- [x]  - detects if the favorites button is clicked
- [x]  - sets the data-view attribute of $ajaxList to 'favorites'
- [x]  - calls the 'loadFavorites' function with the data-model as the argument
- [x] style favorites page so category labels and 'no favorites' message match the rest of the page
- [x] ensure save button does not appear if entry has already been saved
- [x] ensure entry page shows up for items listed in favorites
- [x] ensure entries cannot be saved more than once
- [x] add a function to data.js that saves the data model to local storage whenever the page is refreshed
- [x] add remove entry button to entry page in favorites
- [x] add event listener for remove entry button that removes entry object from data model
- [x] finalize css
- [x] fix any errors
