### ISSUE TITLE
User can search for data by search term

### ISSUE THREAD

**Issue by james-w-roach** [james-w-roach/ajax-project#5]
## ⚙️ Functionality

Adds functionality to the search bar on the main page. Box below search bar will populate with matching or similar results, which lead to corresponding entry page when selected.

## 🖼️ Wireframe

![Screen Shot 2021-02-22 at 5 44 20 PM](https://user-images.githubusercontent.com/76799878/108792529-57ffd580-7536-11eb-882c-a8a6d4d074ec.png)

## ✅ Task List

- [x] Update main.js to account for new API
- [x]  - add different images and logos to match new API
- [x] add basic search bar support:
- [x]  - add a dropdown menu to search bar that let's user select a category
- [x]  - add an event listener that runs the searchAPI function when search is entered
- [x]  - create searchAPI function that formats search to match the API GET format
- [x]  - show the entry page for that character or episode
- [x] add 'no results' page if search doesn't provide any matching results
- [x] update search bar css to match the rest of the site
